#!/bin/bash
# FLCD Platform Development Commands
# Generated by setup-dev-environment.sh

# Start backend development server
start_backend() {
    echo "Starting backend server..."
    cd flcd-backend && npm run dev
}

# Start frontend development server
start_frontend() {
    echo "Starting frontend server..."
    cd flcd-frontend && npm run dev
}

# Start both servers concurrently
start_all() {
    echo "Starting all development servers..."
    (cd flcd-backend && npm run dev) &
    (cd flcd-frontend && npm run dev) &
    wait
}

# Run database migrations
migrate_db() {
    echo "Running database migrations..."
    cd flcd-backend && npm run prisma:migrate
}

# Seed database
seed_db() {
    echo "Seeding database..."
    cd flcd-backend && npm run seed
}

# Run tests
run_tests() {
    echo "Running tests..."
    cd flcd-backend && npm test
    cd ../flcd-frontend && npm run lint
}

# Show usage
show_help() {
    echo "FLCD Platform Development Commands:"
    echo "  start_backend    - Start backend development server"
    echo "  start_frontend   - Start frontend development server"
    echo "  start_all        - Start all development servers"
    echo "  migrate_db       - Run database migrations"
    echo "  seed_db          - Seed database with initial data"
    echo "  run_tests        - Run all tests"
    echo "  show_help        - Show this help message"
}

# If script is called directly, show help
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    show_help
fi
